# Generated by Django 4.0.1 on 2022-02-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.DateField(max_length=100)),
                ('check_in_date', models.DateField(max_length=50)),
                ('check_in_hour', models.TimeField(max_length=50)),
                ('seat', models.CharField(blank=True, max_length=50)),
                ('boarding_gate', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('type_card', models.CharField(max_length=50)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller_app.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.DateField(max_length=100)),
                ('date', models.DateField(max_length=50)),
                ('hour', models.TimeField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=50)),
                ('type_card', models.CharField(max_length=50)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller_app.travel')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackpackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller_app.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.DateField(max_length=100)),
                ('check_in_date', models.DateField(max_length=50)),
                ('check_in_hour', models.TimeField(max_length=50)),
                ('check_out_date', models.DateField(max_length=50)),
                ('check_out_hour', models.TimeField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('type_card', models.CharField(max_length=50)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveller_app.travel')),
            ],
        ),
    ]
