# Generated by Django 4.0.1 on 2022-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_app', '0002_accommodation_latitude_accommodation_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
